task_name: 'arm'

# -- Compute -- #
n_workers: 8

# -- Domain -- #
n_dof: 8
param_bounds: [0, 1]
desc_bounds:
- [0, 1]
- [0, 1]
desc_labels:
- X-Coord
- Y-Coord
iso_sigma: [0.1, 0.1, 0.05, 0.025]

# -- MAP-Elites -- #
grid_res: [25, 25]
n_init: 100
n_gens: 50
n_emitters: 4
n_batch: 25

# -- Logging -- #
print_rate: 1  # Print to console
plot_rate: 10  # Plot graphs
save_rate: 50  # Save archive

