exp_name: 'smoke'

# -- Compute -- #
n_workers: 4

# -- MAP-Elites -- #
grid_res: [10, 10]
n_init: 20
n_gens: 10
n_batch: 10

# -- Logging -- #
print_rate:  1  # Print to console
plot_rate:   2 # Plot graphs
save_rate:   10  # Save archive

