exp_name: 'test'

# -- Compute -- #
n_workers: 8


# -- MAP-Elites -- #
grid_res: [30, 30]
n_init: 100
n_gens: 1000
n_batch: 50

# -- Logging -- #
print_rate: 1  # Print to console
plot_rate: 50  # Plot graphs
save_rate: 200  # Save archive
