name: 'rastrigin'

# -- Compute -- #
n_workers: 4

# -- Domain -- #
dof: 4
param_bounds: [-2, 2]
desc_bounds:
- [-2, 2]
- [-2, 2]
desc_labels:
- [Param 1]
- [Param 2]
mut_strength: 0.1

# -- MAP-Elites -- #
grid_res: [32, 32]
n_init: 512
n_gens: 50
n_emitters: 4
n_batch: 64
# -- Logging -- #
print_rate: 1  # Print to console
plot_rate: 10  # Plot graphs
save_rate: 50  # Save archive

