task_name: 'arm'

# -- Domain -- #
n_dof: 8
param_bounds: [0, 1]

# -- Archives -- #
archive:
  type: "CVT"
  n_bins: 350
  desc_bounds:
  - [0, 1]
  - [0, 1]
  desc_labels:
  - X-Coord
  - Y-Coord

# -- Emitters -- #
emitters:
  -
    name: "CMA-1"
    type: "Cma"
    batch_size: 50
    sigma0: 0.005
  -
    name: "CMA-2"
    type: "Cma"
    batch_size: 50
    sigma0: 0.005     

# -- Logging -- #
print_rate: 1  # Print to console
plot_rate: 10  # Plot graphs
save_rate: 50  # Save archive

