task_name: 'rastrigin'

# -- Optimization -- #
n_init: 100
n_gens: 500

# -- Parameters -- #
n_dof: 10
param_bounds: [-2, 2]

# -- Archive -- #
archive:
  type: "Grid"
  grid_res: [20,20]
  desc_bounds:
  - [-2, 2]
  - [-2, 2]
  desc_labels:
  - Param 1
  - Param 2  

# -- Emitters -- #
emitters:
  -
    name: "Gaussian-01"
    type: "Gauss"
    batch_size: 25
    sigma0: 0.01
  -
    name: "Gaussian-05"
    type: "Gauss"
    batch_size: 25
    sigma0: 0.05    


# -- Logging -- #
print_rate: 5  # Print to console
plot_rate: 25  # Plot graphs
save_rate: 50  # Save archive

