exp_name: 'gaussian'

# -- Emitters -- #
emitters:
  -
    name: "Gaussian-01"
    type: "Gauss"
    batch_size: 50
    sigma0: 0.01
  -
    name: "Gaussian-05"
    type: "Gauss"
    batch_size: 50
    sigma0: 0.05