exp_name: 'line'

emitters:
  -
    name: "Line-0005"
    type: "Line"
    batch_size: 50
    iso_sigma: 0.005
    line_sigma: 0.05
  -
    name: "Line-0001"
    type: "Line"
    batch_size: 50
    iso_sigma: 0.001
    line_sigma: 0.05