exp_name: 'line'

emitters:
  -
    name: "Line1"
    type: "Line"
    batch_size: 50
    iso_sigma: 0.005
    line_sigma: 0.1
  -
    name: "Line2"
    type: "Line"
    batch_size: 50
    iso_sigma: 0.001
    line_sigma: 0.1