exp_name: 'line'

emitters:
  -
    name: "Line-005"
    type: "Line"
    batch_size: 50
    iso_sigma: 0.005
    line_sigma: 0.1
  -
    name: "Line-001"
    type: "Line"
    batch_size: 50
    iso_sigma: 0.001
    line_sigma: 0.1