exp_name: 'line_cma_mix'

emitters:
  -
    name: "CMA-005"
    type: "Cma"
    batch_size: 50
    sigma0: 0.005
  -
    name: "Line-005"
    type: "Line"
    batch_size: 50
    iso_sigma: 0.005
    line_sigma: 0.1