exp_name: 'line_cma_mix'

emitters:
  -
    name: "CMA-1"
    type: "Cma"
    batch_size: 25
    sigma0: 0.005
  -
    name: "Line1"
    type: "Line"
    batch_size: 25
    iso_sigma: 0.005
    line_sigma: 0.1