task_name: 'rastrigin'

# -- Compute -- #
n_workers: 1

# -- Domain -- #
n_dof: 10
param_bounds: [-2, 2]
desc_bounds:
- [-2, 2]
- [-2, 2]
desc_labels:
- Param 1
- Param 2


emitters:
  -
    name: "Imp1"
    type: "Improvement"
    n_batch: 50
    sigma0: 0.01
  -
    name: "Imp2"
    type: "Improvement"
    n_batch: 50
    sigma0: 0.005

# -- MAP-Elites -- #
grid_res: [20, 20]
n_init: 100
n_gens: 50
n_emitters: 4
n_batch: 25

# -- Logging -- #
print_rate: 1  # Print to console
plot_rate: 10  # Plot graphs
save_rate: 50  # Save archive

