task_name: 'rastrigin_obj'

# -- Optimization -- #
n_init: 100
n_gens: 50

# -- Parameters -- #
n_dof: 10
param_bounds: [-2, 2]

# -- Archive -- #
archive:
  type: "Grid"
  grid_res: [20,20]
  desc_bounds:
  - [-2, 2]
  - [-2, 2]
  desc_labels:
  - Param 1
  - Param 2  
  use_objects: True

# -- Emitters -- #
emitters:
  -
    name: "Obj1"
    type: "Object"
    batch_size: 50
    mut_p:      
      iso_sigma: 0.01

# -- Logging -- #
print_rate: 1  # Print to console
plot_rate: 10  # Plot graphs
save_rate: 50  # Save archive

