exp_name: 'smoke'

# -- Compute -- #
n_workers: 1

# -- MAP-Elites -- #
grid_res: [10, 10]
n_init: 20
n_gens: 10


emitters:
  -
    name: "Line1"
    type: "Line"
    n_batch: 50
    sigma0: 0.005


# -- Logging -- #
print_rate:  1  # Print to console
plot_rate:   10 # Plot graphs
save_rate:   10  # Save archive

