exp_name: 'test'


# -- Domain -- #
#n_dof: 8

# -- MAP-Elites -- #
grid_res: [20, 20]
n_init: 100
n_gens: 500

# -- Logging -- #
print_rate: 10  # Print to console
plot_rate:  50  # Plot graphs
save_rate:  500  # Save archive

