exp_name: 'smoke'

# -- Compute -- #
n_workers: 1

# -- MAP-Elites -- #
n_init: 25
n_gens: 10

# -- Emitters -- #
# emitters:
#   -
#     name: "Line1"
#     type: "Line"
#     batch_size: 10
#     iso_sigma: 0.005


# -- Logging -- #
print_rate:  1  # Print to console
plot_rate:   5  # Plot graphs
save_rate:   10 # Save archive

