exp_name: 'cmame'

# -- Emitters -- #
emitters:
  -
    name: "CMA-005"
    type: "Cma"
    batch_size: 50
    sigma0: 0.005
  -
    name: "CMA-001"
    type: "Cma"
    batch_size: 50
    sigma0: 0.001    